### ISSUE TITLE
please provide linuxcontainer only environment? 

### ISSUE THREAD

**Issue by dkmbw** [keycloak/keycloak-demo#10]
Hi,
i have a windows laptop and tried your demo with minishift. There are several problems:

- with windows i have to add to minishift --vm-driver virtualbox to start-minishift.sh
- with windows i have to add slashes in start-keycloak.sh when subjects are given to openssl due to weird behaviour of windows with the slash.. (like -subj "//CN=keycloak-keycloak.${OC_PUBLIC_IP}.nip.io")
- the container proxy in the demo-service-php pod is crash looping. (atm i do not know why)

It would be really need, if you could provide the demo with docker-ce or minikube (with vm-driver=none), since both can run natively WITHIN a virtual machine with a linux guest.

**Comment by stianst** [comment]
Hi, this is a temporary solution and we are moving towards an interactive tutorial (Katacoda) soon that will not require installing anything locally to try things out. Once we have the interactive tutorial ready we are going to consider adding a local install option that will only require containers.

Closing this issue as this repository will soon be replaced by the interactive Katacoda tutorial.
