### ISSUE TITLE
Issue starting minishift using the instructions in the README of keycloak-demo

### ISSUE THREAD

**Issue by Rovanion** [keycloak/keycloak-demo#4]
Trying to follow the instructions in the README on commit `ff546d65e611d0123d04696a7f7fccb59f242801` from the top on my Ubuntu 18.04 I've encountered an error when `bin/start-minishift.sh` tries to apply the addon `admin-user`:

```
┌[rovanion][Machine79][master]:~/source/java/keycloak-demo 
└$ minishift addon apply admin-user
Error applying the add-on: The specified path to the kube config '/home/rovanion/.minishift/machines/minishift_kubeconfig' does not exist
```

That command is the fifth line of `bin/start-minishift.sh` which in turn the user is instructed to run in the fourth paragraph of the first chapter in the README.

Version info:
```
┌[rovanion][Machine79][master]:~/source/java/keycloak-demo 
└$ minishift version
minishift v1.26.1+1e20f27
┌[rovanion][Machine79][master]:~/source/java/keycloak-demo 
└$ uname -a
Linux Machine79 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
┌[rovanion][Machine79][master]:~/source/java/keycloak-demo 
└$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by ckromero** [comment]
same issue:
--> minishift version
minishift v1.28.0+48e89ed

**Comment by stianst** [comment]
Hi, this is a temporary solution and we are moving towards an interactive tutorial (Katacoda) soon that will not require installing anything locally to try things out. Once we have the interactive tutorial ready we are going to consider adding a local install option that will only require containers.

Closing this issue as this repository will soon be replaced by the interactive Katacoda tutorial.
